SELECT s.NAME, s.ADDRESS
FROM STUDIO s
WHERE s.NAME IN (SELECT m.STUDIONAME FROM MOVIE m WHERE INCOLOR = 'Y')
INTERSECT
SELECT s.NAME, s.ADDRESS
FROM STUDIO s
WHERE s.NAME IN (SELECT m.STUDIONAME FROM MOVIE m WHERE INCOLOR = 'N');

SELECT s.NAME, s.ADDRESS, AVG(m.LENGTH)
FROM STUDIO s
JOIN MOVIE m ON s.NAME = m.STUDIONAME
WHERE s.NAME IN (SELECT STUDIONAME
                FROM MOVIE M
                GROUP BY STUDIONAME
                HAVING COUNT(TITLE) <= 3)
GROUP BY s.NAME, s.ADDRESS;
