CREATE TABLE PERSON
(
    NUMBER INT         NOT NULL PRIMARY KEY,
    NAME   VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENT
(
    NUMBER INT      NOT NULL PRIMARY KEY REFERENCES PERSON (NUMBER),
    CARDNO CHAR(16) NOT NULL
);

CREATE TABLE OWNER
(
    NUMBER INT      NOT NULL PRIMARY KEY REFERENCES PERSON (NUMBER),
    IBAN   CHAR(22) NOT NULL
);

CREATE TABLE PROPERTY
(
    NUMBER      INT          NOT NULL PRIMARY KEY,
    ADDRESS     VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(50)  NOT NULL,
    PRICE       INT          NOT NULL CHECK (PRICE >= 0),
    STATUS      INT          NOT NULL CHECK (STATUS IN (0, 1)),
    OWNER_NO    INT          NOT NULL REFERENCES OWNER (NUMBER)
);

CREATE TABLE RENTS
(
    CNUMBER INT  NOT NULL REFERENCES CLIENT (NUMBER),
    PNUMBER INT  NOT NULL REFERENCES PROPERTY (NUMBER),
    SDATE   DATE NOT NULL,
    EDATE   DATE NOT NULL,
    PRIMARY KEY (CNUMBER, PNUMBER)
);
