SELECT S.NAME, COUNT(M.TITLE) as CNT
FROM STUDIO S JOIN MOVIE M
ON S.NAME = M.STUDIONAME
GROUP BY S.NAME
HAVING COUNT(M.TITLE) < 2;

SELECT me.NAME
FROM MOVIEEXEC me
WHERE me.NETWORTH = (SELECT MIN(NETWORTH) FROM MOVIEEXEC);