CREATE TABLE CLIENTS
(
    PHONE CHAR(12)    NOT NULL PRIMARY KEY,
    NAME  VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL
);

CREATE TABLE OFFICES
(
    CODE    CHAR(5)     NOT NULL PRIMARY KEY,
    NAME    VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLOYEES
(
    NUMBER      CHAR(5)     NOT NULL PRIMARY KEY,
    NAME        VARCHAR(30) NOT NULL,
    PHONE       CHAR(12)    NOT NULL,
    OFFICE_CODE CHAR(5)     NOT NULL REFERENCES OFFICES (CODE)
);

CREATE TABLE AUTOMOBILE
(
    LICENCE_NUMBER CHAR(8)       NOT NULL PRIMARY KEY,
    BRAND          VARCHAR(15)   NOT NULL,
    MODEL          VARCHAR(15)   NOT NULL,
    PRICE          DECIMAL(9, 2) NOT NULL CHECK (PRICE > 0),
    OFFICE_CODE    CHAR(5)       NOT NULL REFERENCES OFFICES (CODE)
);

CREATE TABLE BOOK
(
    PHONE          CHAR(12) NOT NULL REFERENCES CLIENTS (PHONE),
    LICENCE_NUMBER CHAR(8)  NOT NULL REFERENCES AUTOMOBILE (LICENCE_NUMBER),
    SDATE          DATE     NOT NULL,
    EDATE          DATE     NOT NULL,
    PAID           DECIMAL(9, 2),
    PRIMARY KEY (PHONE, LICENCE_NUMBER)
);