CREATE TABLE PERSON
(
    NUMBER INT         NOT NULL PRIMARY KEY,
    NAME   VARCHAR(50) NOT NULL
);

CREATE TABLE PATIENT
(
    NUMBER INT NOT NULL PRIMARY KEY REFERENCES PERSON (NUMBER)
);

CREATE TABLE DENTIST
(
    NUMBER INT NOT NULL PRIMARY KEY REFERENCES PERSON (NUMBER)
);

CREATE TABLE SERVICE
(
    DENTIST_NUMBER INT          NOT NULL REFERENCES DENTIST (NUMBER),
    NUMBER         INT          NOT NULL,
    DESCRIPTION    VARCHAR(100) NOT NULL,
    PRICE          DOUBLE       NOT NULL,
    PRIMARY KEY (DENTIST_NUMBER, NUMBER)
);

CREATE TABLE APPOINTMENT
(
    PATIENT_NUMBER INT NOT NULL REFERENCES PATIENT (NUMBER),
    DENTIST_NUMBER INT NOT NULL REFERENCES SERVICE (DENTIST_NUMBER),
    SERVICE_NUMBER INT NOT NULL REFERENCES SERVICE (NUMBER),
    ADATE DATE NOT NULL,
    ATIME TIME NOT NULL,
    PROBLEMS VARCHAR(50) NOT NULL,
    PRIMARY KEY (PATIENT_NUMBER, DENTIST_NUMBER, ADATE, ATIME)
);