SELECT me.NAME, m.YEAR, COUNT(m.TITLE) AS NUMBER_MOVIES
FROM MOVIEEXEC me
JOIN MOVIE m ON m.PRODUCERC# = me.CERT#
GROUP BY me.NAME, m.YEAR
HAVING COUNT(m.TITLE) >= 1;

SELECT NAME, BIRTHDATE
FROM MOVIESTAR
WHERE BIRTHDATE = (SELECT MAX(BIRTHDATE) FROM MOVIESTAR);