CREATE TABLE CLIENT (
    PHONE CHAR(10) NOT NULL PRIMARY KEY,
    NAME NVARCHAR(50)
);

CREATE TABLE OFFICE (
    NAME NVARCHAR(30) NOT NULL PRIMARY KEY,
    CITY NVARCHAR(20),
    STREET NVARCHAR(30)
);

CREATE TABLE COURIER (
  NUMBER CHAR(5) NOT NULL PRIMARY KEY,
  NAME VARCHAR(30),
  OFFICE_NAME NVARCHAR(30) REFERENCES OFFICE(NAME)
);

CREATE TABLE PACKAGE (
    NUMBER CHAR(10) NOT NULL PRIMARY KEY,
    ADDRESS VARCHAR(30),
    STATUS CHAR(10),
    TAX DOUBLE,
    SPHONE CHAR(10) REFERENCES CLIENT(PHONE),
    RPHONE CHAR(10) REFERENCES CLIENT(PHONE),
    SDATE DATE,
    RDATE DATE,
    SOFFICE NVARCHAR(30) REFERENCES OFFICE(NAME),
    ROFFFICE NVARCHAR(30) REFERENCES OFFICE(NAME),
    COURIERNUMBER CHAR(5) REFERENCES COURIER(NUMBER)
);
